<?php
/**
 * Cookies registry screen.
 *
 * @package Zen_Cookie_Keeper
 * @var array $grouped     Catalog grouped by platform.
 * @var array $unsupported Explicitly unsupported cookies (name => reason).
 * @var array $formats     Current mint/capture format rules.
 */

if (!defined('ABSPATH')) {
    exit;
}
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Template variables are local to Admin::view(), which includes this file; they are not global.
?>
<div class="wrap zenck-wrap">
    <h1><?php esc_html_e('Managed cookies', 'zen-cookie-keeper'); ?></h1>
    <p class="description"><?php esc_html_e('Toggle each cookie, set its lifetime to match your privacy policy, and add your own. The anchor cookie is not listed here — it is managed automatically (see Overview).', 'zen-cookie-keeper'); ?></p>

    <div class="zenck-help zenck-source-help">
        <h3><?php esc_html_e('What "Source" means', 'zen-cookie-keeper'); ?></h3>
        <p><strong><?php esc_html_e('Mint', 'zen-cookie-keeper'); ?></strong> — <?php esc_html_e('the value is built on your server from a click parameter in the landing URL (for example, ?gclid=… becomes _gcl_aw). Because it is a server write rather than a JavaScript one, the browser\'s 24-hour cap on script-set cookies does not apply.', 'zen-cookie-keeper'); ?></p>
        <p><strong><?php esc_html_e('Capture', 'zen-cookie-keeper'); ?></strong> — <?php esc_html_e('the value cannot be derived from a URL — it is generated in the visitor\'s browser by the platform\'s own tag (gtag for _ga, the Meta pixel for _fbp, the TikTok pixel for _ttp). The companion script reads that value and the plugin re-sets it server-side so it lasts the full lifetime.', 'zen-cookie-keeper'); ?></p>
    </div>

    <p><button class="button button-primary" id="zenck-add-custom-btn"><?php esc_html_e('Add custom cookie', 'zen-cookie-keeper'); ?></button></p>

    <?php foreach ($grouped as $platform => $cookies) : ?>
        <div class="zenck-platform">
            <h2 class="zenck-platform-head"><?php echo esc_html($platform); ?></h2>
            <table class="widefat striped zenck-registry">
                <thead>
                    <tr>
                        <th><?php esc_html_e('Cookie', 'zen-cookie-keeper'); ?></th>
                        <th><?php esc_html_e('Purpose', 'zen-cookie-keeper'); ?></th>
                        <th><?php esc_html_e('Source', 'zen-cookie-keeper'); ?></th>
                        <th><?php esc_html_e('Lifetime', 'zen-cookie-keeper'); ?> <span class="zenck-hint" title="<?php esc_attr_e('This must match your privacy policy.', 'zen-cookie-keeper'); ?>">?</span></th>
                        <th><?php esc_html_e('HttpOnly', 'zen-cookie-keeper'); ?> <span class="zenck-hint" title="<?php esc_attr_e('Leave off for cookies a pixel must read in the browser (e.g. _ga, _fbp).', 'zen-cookie-keeper'); ?>">?</span></th>
                        <th><?php esc_html_e('Enabled', 'zen-cookie-keeper'); ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($cookies as $name => $spec) :
                    $days = max(1, (int) round($spec['lifetime'] / DAY_IN_SECONDS)); ?>
                    <tr data-cookie="<?php echo esc_attr($name); ?>">
                        <td><code><?php echo esc_html($name); ?></code><br><span class="description"><?php echo esc_html($spec['label']); ?></span></td>
                        <td><span class="zenck-badge zenck-badge-<?php echo esc_attr($spec['bucket']); ?>"><?php echo esc_html($spec['bucket']); ?></span></td>
                        <td>
                            <span class="zenck-source"><?php echo esc_html($spec['source']); ?></span>
                            <?php if ($spec['source'] === 'capture') : ?>
                                <span class="zenck-hint" title="<?php esc_attr_e('Cannot be minted from a URL — its value is generated by gtag, so the companion captures it.', 'zen-cookie-keeper'); ?>">?</span>
                            <?php endif; ?>
                        </td>
                        <td><input type="number" min="1" class="small-text zenck-lifetime" value="<?php echo esc_attr($days); ?>"> <?php esc_html_e('days', 'zen-cookie-keeper'); ?></td>
                        <td><input type="checkbox" class="zenck-httponly" <?php checked(!empty($spec['httponly'])); ?> <?php disabled($spec['bucket'] !== '' && in_array($name, array('_ga', '_fbp'), true)); ?>></td>
                        <td>
                            <label class="zenck-switch">
                                <input type="checkbox" class="zenck-toggle" <?php checked(!empty($spec['status'])); ?>>
                                <span class="zenck-slider"></span>
                            </label>
                            <?php if (!empty($spec['custom'])) : ?>
                                <a href="#" class="zenck-delete-custom" data-cookie="<?php echo esc_attr($name); ?>"><?php esc_html_e('delete', 'zen-cookie-keeper'); ?></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endforeach; ?>

    <h2><?php esc_html_e('Not supported', 'zen-cookie-keeper'); ?></h2>
    <table class="widefat striped zenck-unsupported">
        <tbody>
        <?php foreach ($unsupported as $name => $reason) : ?>
            <tr><td><code><?php echo esc_html($name); ?></code></td><td><?php echo esc_html($reason); ?></td></tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <h2><?php esc_html_e('Advanced: mint formats', 'zen-cookie-keeper'); ?></h2>
    <p class="description"><?php esc_html_e('Platform cookie formats drift over time. Edit the JSON rules here so you can adapt without a plugin update. Each rule may set source, param, template ({ts}, {value}) and value_regex.', 'zen-cookie-keeper'); ?></p>
    <textarea id="zenck-formats" class="large-text code zenck-formats" rows="12"><?php echo esc_textarea(wp_json_encode($formats, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)); ?></textarea>
    <p><button class="button" id="zenck-save-formats"><?php esc_html_e('Save formats', 'zen-cookie-keeper'); ?></button> <span class="zenck-result" id="zenck-formats-result"></span></p>

    <?php require ZEN_COOKIE_KEEPER_PATH . 'admin/views/custom-cookie-modal.php'; ?>
</div>
