<?php
/**
 * Capture intake for Zen Cookie Keeper.
 *
 * For cookies the server cannot mint from a URL (chiefly _ga, whose client_id is
 * generated by gtag), the JS companion posts the value gtag wrote and we store
 * it once. The value is format-validated per cookie (anti-injection) and bound
 * to the anchor; first_seen_ts is the first-seen marker and is never recomputed.
 *
 * @package Zen_Cookie_Keeper
 */

if (!defined('ABSPATH')) {
    exit;
}

class Zen_Cookie_Keeper_Capture {

    /**
     * Validate + store a captured value once.
     *
     * @param int    $anchor_id
     * @param string $cookie_name
     * @param string $raw_value   Untrusted, from the companion POST.
     * @param array  $spec        Catalog spec for the cookie.
     * @return string 'inserted'|'exists'|'rejected'|'failed'
     */
    public static function receive($anchor_id, $cookie_name, $raw_value, $spec) {
        $custom_regex = isset($spec['value_regex']) ? $spec['value_regex'] : '';

        if (!Zen_Cookie_Keeper_Formats::validate_value($cookie_name, $raw_value, $custom_regex)) {
            // Silently reject forged / malformed values; log for diagnostics.
            Zen_Cookie_Keeper_Store::instance()->insert_op('capture', $cookie_name, 'rejected', $anchor_id);
            return 'rejected';
        }

        $result = Zen_Cookie_Keeper_Store::instance()->store_value_once(
            $anchor_id,
            $cookie_name,
            $raw_value,
            $spec['bucket'],
            'capture',
            time(),
            (int) $spec['lifetime']
        );

        Zen_Cookie_Keeper_Store::instance()->insert_op('capture', $cookie_name, $result, $anchor_id);
        return $result;
    }
}
